---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fyp-frontend
  namespace: default
  labels:
    app: fyp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fyp-frontend
  template:
    metadata:
      labels:
        app: fyp-frontend
    spec:
      containers:
      - name: fyp-frontend
        image: "unclechuen/fyp-frontend"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fyp-frontend
  namespace: default
spec:
  selector:
    app: fyp-frontend
  type: NodePort
  ports:
  - name: http
    targetPort: 3000
    port: 3000 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: mini-echo.io
    http:
      paths:
      - path: /
        backend:
          serviceName: echoserver
          servicePort: 8080
  - host: mini-web.io
    http:
      paths:
      - path: /echo
        backend:
          serviceName: echoserver
          servicePort: 8080
